### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by SamaraFellaDina** [Naddybs/proof-of-concept#2]
# [`index.ejs`](https://github.com/Naddybs/proof-of-concept/blob/main/views/index.ejs)
* Button moet een form omheen, wil je er gebruik van maken. Ik weet niet precies wat je wilt maken, maar soms kan je voor verschillende interacties een `<a>` gebruiken. Voor bijvoorbeeld een anchor punt. 
https://github.com/Naddybs/proof-of-concept/blob/f105dc7582eb944057f4769f7872bd85c56f0e1a/views/index.ejs#L7

* `section` moet een heading hebben.
  * [Hier](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) heb je een artikel van MDN die laat zien hoe je deze precies moet gebruiken. Kan je ook een aantal voorbeelden zien :)
https://github.com/Naddybs/proof-of-concept/blob/f105dc7582eb944057f4769f7872bd85c56f0e1a/views/index.ejs#L10-L22

* Als je een `section` maakt met de `class="article"`, kan je dan niet beter een `article` element gebruiken?
  * Het `article` element staat eigenlijk voor een object die dus een bericht wilt weergeven, [MDM](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article) heeft hiervan een goede uitleg. Misschien krijg je dan een goede visie over hoe je dit element kan gebruiken
https://github.com/Naddybs/proof-of-concept/blob/f105dc7582eb944057f4769f7872bd85c56f0e1a/views/index.ejs#L24-L35

# [`styles.css`](https://github.com/Naddybs/proof-of-concept/blob/main/public/styles/styles.css)
* Goed dat je gebruik maakt van nested css
* Ik zie dat dit element vaak terugkomt, zou je hier anders geen `custom property` van kunnen maken?
https://github.com/Naddybs/proof-of-concept/blob/f105dc7582eb944057f4769f7872bd85c56f0e1a/public/styles/styles.css#L62

## Algemene tips
* Zorg dat je code goed dry blijft
  * zorg dat je eerst de basiselementen stijlt, waarna je steeds dieper gaat werken
  * Zorg ervoor dat je niet te veel herhaalt, dus maak gebruik van `custom properties` Dit zou ook in een parent eventueel kunnen, het hoeft niet allemaal in de `:root` te zitten.

### Voorbeeld van `custom properties`
Ik heb in mijn vorige sprint er uitgebreid mee gewerkt. Mijn `:root` zag er toen zo uit:
```css
:root {
  --primary-color-1: #2e2e2e;
  --primary-color-2: #747474;
  --primary-color-4: #f7f7f5;
  --primary-color-3: #d9d9d9;
  --active-color-1: #e85340;
  --active-color-1_hover: #53211a;


  --secondary-color-1: #5340e8;
  --secondary-color-2: #f2d930;


  --font-sans-serif: "Inter", arial, sans-serif;
  --font-serif: "Merriweather", Georgia, serif;
  --border-style-black: 2px solid var(--primary-color-1);
  --border-style-white: 2px solid var(--primary-color-3);


  --default-padding: 1em;


  --transition-flow: 0.5s ease-out, color 0.1s ease;
}
```

Waarna ik dus ook specifieker in parents ging werken, dat zag er zo uit:
```css
#navbar-toggle .navbar-menu-button {
  --transition: 0.5s cubic-bezier(0.77, 0.2, 0.05, 1);


  display: block;
  width: 33px;
  height: 4px;
  margin-bottom: 5px;
  position: relative;
  background: var(--primary-color-1);
  border-radius: 3px;
  z-index: 1;


  transform-origin: 4px 0px;
  transition: transform var(--transition), background var(--transition),
    opacity 0.55s ease;
}


#navbar-toggle .navbar-menu-button:first-child {
  transform-origin: 0% 0%;
}


#navbar-toggle .navbar-menu-button:nth-last-child(2) {
  transform-origin: 0% 100%;
}
```

Misschien krijg je zo een duidelijke visie over hoe je het precies zou kunnen gebruiken. In ieder geval al erg goed bezig :)
  
Keep it going!!❤️

![](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExaHAycmh1MGM3eXkxMmlvZnd3Z21zcmRtcnZubWhyZHdoNXR2dWwweCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/VnaMMuJt5jbmE/giphy.webp)
